<?xm version='1.0' encoding='UTF-8'?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:tns="http://wsdl.javaee7.jaxws.tjonahen.nl" 
             xmlns:ns1="http://javaee7.jaxws.tjonahen.nl" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             targetNamespace="http://wsdl.javaee7.jaxws.tjonahen.nl" 
             name="WS">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://javaee7.jaxws.tjonahen.nl" schemaLocation="service.xsd"/>
        </xsd:schema>
    </types>
    
    <message name="wsRequest">
        <part name="parameters" element="ns1:wsRequest"/>
    </message>
    <message name="wsResponse">
        <part name="parameters" element="ns1:wsResponse"/>
    </message>
    <message name="wsFault">
        <part name="fault" element="ns1:wsFault"/>
    </message>
    
    <portType name="WSPort">
        <operation name="triggerFilter">
            <input  message="tns:wsRequest"/>
            <output message="tns:wsResponse"/>
            <fault message="tns:wsFault" name="fault" />
        </operation>
    </portType>
    
    <binding name="WSPortBinding" type="tns:WSPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="triggerFilter">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal"/>
            </fault>
        </operation>
        
    </binding>
    
    <service name="WSService">
        <port name="WSPort" binding="tns:WSPortBinding">
            <soap:address location="TBF"/>
        </port>
    </service>
</definitions>
