DROP TABLE "USERS_GROUPS";
DROP TABLE "GROUPS";
DROP TABLE "USERS";

-- The user tabel add users with MD5 hashed passwords
CREATE TABLE USERS (
        USERID VARCHAR(50) NOT NULL PRIMARY KEY,
        PASSWORD VARCHAR(128) NOT NULL
    );
-- The groups table
CREATE TABLE GROUPS (
        GROUPID VARCHAR(20) NOT NULL PRIMARY KEY
    );

-- The join table, this is the groups table you must specify when creating the jdbcDigestRealm
CREATE TABLE USERS_GROUPS (
        GROUPID VARCHAR(20) NOT NULL,
        USERID VARCHAR(50) NOT NULL
    );

-- Join table foreign key constraints

ALTER TABLE "USERS_GROUPS"
ADD CONSTRAINT FK_USERS_GROUPS_PERSON
FOREIGN KEY (USERID)
REFERENCES "USERS"(USERID)
;
ALTER TABLE "USERS_GROUPS"
ADD CONSTRAINT FK_USERS_GROUPS_GROUPS
FOREIGN KEY (GROUPID)
REFERENCES "GROUPS"(GROUPID)
;


